version: "3"
services:
    frontend:
        container_name: aircnc_web
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: aircnc_web
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/usr/src/app
        # networks: 
        #     - default
    backend:
        container_name: aircnc_server
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: aircnc_server
        ports:
            - "3333:3333"
        volumes:
            - ./backend:/usr/src/app
        # networks: 
        #     - default
    mongodb:
        container_name: mongo
        image: mongo
        volumes:
            - ./mongo_db:/data/db
        environment:
            - MONGO_DATA_DIR=/data/db
        ports:
            - 27017:27017
#         networks: 
#             - default
# networks: 
#     default:
        # - production-network
        # driver: frontend_default